attack:
	@pip install pyfinite
	@pip install numpy
	@sudo apt install sshpass
	@rm -f plaintext.txt
	@rm -f ciphertext.txt
	@python3 Plaintext_generation.py
	@sh command.sh
	@python3 Ciphertext_generation.py
	@python3 EAES_ALGO.py